/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    CalculatorSection: typeof import('./components/CalculatorSection.vue')['default']
    CtaSection: typeof import('./components/CtaSection.vue')['default']
    FeaturesSection: typeof import('./components/FeaturesSection.vue')['default']
    ForInvestorsSection: typeof import('./components/ForInvestorsSection.vue')['default']
    HeroSection: typeof import('./components/HeroSection.vue')['default']
    HowItWorksSection: typeof import('./components/HowItWorksSection.vue')['default']
    PainSection: typeof import('./components/PainSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionNav: typeof import('./components/SectionNav.vue')['default']
    TrustSection: typeof import('./components/TrustSection.vue')['default']
  }
}
